on: [push]
jobs:
  build-all:
    runs-on: debian-latest
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3 cmake ninja-build libsdl2-dev libspdlog-dev libvulkan-dev
      - name: checkout code
        uses: actions/checkout@v4
      - name: build
        run: |
          mkdir build
          cd build
          cmake -G Ninja -DCMAKE_BUILD_TYPE=Release ..
          cmake --build . -j8