on: [push]
jobs:
  build-all:
    runs-on: docker
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make