on: [push]
jobs:
  build-all:
    runs-on: docker
    steps:
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y cmake libsdl2-dev libspdlog-dev
      - name: checkout code
        uses: actions/checkout@v4
      - name: build
        run: |
          mkdir build
          cd build
          cmake ..
          make